import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync(new URL('../mta-scan/static/index.html',import.meta.url),'utf8');
const script=readFileSync(new URL('../mta-scan/static/temporal-view.js',import.meta.url),'utf8');
function example(){const now=Math.floor(Date.now()/1000);return {schema:'mta-temporal-evaluation-v1',generated_ts:now,valid_until_ts:now+500,readiness:{status:'ready',public_forecasts_ready:true,reasons:[]},coverage:{span_seconds:15*86400},forecasts:[{route_id:'A',direction:'platform:N',horizon_seconds:900,origin_ts:now-100,target_ts:now+800,predicted_proxy_seconds:180,algorithm:'persistence'}],metrics:[]};}
async function setup(value){const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const callbacks=[];dom.window.setInterval=(fn)=>callbacks.push(fn);dom.window.fetch=async()=>({ok:true,json:async()=>value});dom.window.eval(script);await new Promise(r=>setImmediate(r));return {dom,doc:dom.window.document,callbacks};}
test('current proxy renders safe text and expires independently of fetch',async()=>{const value=example();const {dom,doc,callbacks}=await setup(value);try{assert.equal(doc.getElementById('temporalForecastTable').hidden,false);assert.match(doc.getElementById('temporalForecastRows').textContent,/180 s/);value.valid_until_ts=1;callbacks[1]();assert.equal(doc.getElementById('temporalForecastTable').hidden,true);assert.equal(doc.getElementById('temporalForecastRows').children.length,0);}finally{dom.window.close();}});
test('ready=false clears array even if stale worker sent rows; labels never become markup',async()=>{const value=example();value.readiness.public_forecasts_ready=false;value.readiness.reasons=['<img src=x onerror=alert(1)>'];const {dom,doc}=await setup(value);try{assert.equal(doc.getElementById('temporalForecastRows').children.length,0);assert.equal(doc.querySelector('#temporalReasons img'),null);assert.match(doc.getElementById('temporalReasons').textContent,/<img/);}finally{dom.window.close();}});
test('unknown schema fails closed and preserves independent live workspace',async()=>{const {dom,doc}=await setup({schema:'unknown'});try{assert.equal(doc.getElementById('temporalStatus').textContent,'Temporarily unavailable');assert.equal(doc.getElementById('temporalForecastTable').hidden,true);assert.ok(doc.getElementById('map'));}finally{dom.window.close();}});
test('missing seasonal scores remain unmeasured, and selected score is explicit',async()=>{const value=example();value.readiness.public_forecasts_ready=false;value.coverage.span_seconds=3600;const measure={n:10,eligible_pairs:12,mae_seconds:20,rmse_seconds:25,coverage_fraction:10/12};value.metrics=[{partition:'test',horizon_seconds:900,models:{persistence:measure,seasonal_24h:{n:0,eligible_pairs:12,mae_seconds:null,rmse_seconds:null,coverage_fraction:0},online_linear:measure},selected_from_validation:measure}];const {dom,doc}=await setup(value);try{const rows=[...doc.getElementById('temporalMetricRows').children];assert.equal(rows.length,4);assert.equal(rows[1].children[2].textContent,'—');assert.match(rows[3].textContent,/Validation-selected/);assert.match(doc.getElementById('temporalEvaluationNote').textContent,/Short-window feasibility/);}finally{dom.window.close();}});
