import test,{before,after}from'node:test';
import assert from'node:assert/strict';
import{createServer}from'node:http';
import{readFile,mkdir}from'node:fs/promises';
import{resolve,sep,extname}from'node:path';
const engines=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const ROOT=resolve(process.env.DEMO_SOURCES_ROOT||'.');
let browser,server,BASE;
before(async()=>{server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(req.method!=='GET'||!path.startsWith('/deid/')||path.includes('/api/')){res.writeHead(404);res.end();return;}const base=resolve(ROOT,'deid/static'),file=resolve(base,path.slice(6)||'index.html');if(!file.startsWith(base+sep))throw new Error();const bytes=await readFile(file);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[extname(file)]||'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));BASE='http://127.0.0.1:'+server.address().port;const name=process.env.UI_BROWSER||'chromium';browser=await engines[name].launch({headless:true,...(name==='chromium'&&process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});});
after(async()=>{await browser?.close();server?.closeAllConnections();await new Promise(r=>server?server.close(r):r());});
const source='😀 Avery emails demo@example.invalid. Reference ZX91.';
const span=(text,value)=>{const i=text.indexOf(value);const start=Array.from(text.slice(0,i)).length;return[start,start+Array.from(value).length];};
const examples={examples:[{title:'Synthetic review fixture',blurb:'Fictional text used only by browser tests.',text:source}],policy_map:{PERSON:'redact',EMAIL:'hash'},limits:{max_text_chars:6000,max_body_bytes:32768}};
function response(text=source){const rows=[{label:'PERSON',span:span(text,'Avery'),detector:'spacy',action:'redact',replacement:'[REDACTED:PERSON]'},{label:'EMAIL',span:span(text,'demo@example.invalid'),detector:'regex',action:'hash',replacement:'EMAIL_HASH:synthetic-fixture'}];let end=0;const chars=Array.from(text),parts=[];for(const e of rows){parts.push(chars.slice(end,e.span[0]).join(''),e.replacement);end=e.span[1];}parts.push(chars.slice(end).join(''));return{result_text:parts.join(''),entities:rows,time_ms:7,original_len:chars.length};}
async function open(width=1440,height=900,handler){const context=await browser.newContext({viewport:{width,height},isMobile:width<600,hasTouch:width<600,reducedMotion:'reduce',acceptDownloads:true});await context.route('**/*',r=>new URL(r.request().url()).origin===BASE?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=0;await page.addInitScript(()=>{window.__copies=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.__copies.push(value)}});});await page.route('**/api/examples',r=>r.fulfill({json:examples}));await page.route('**/api/deidentify',r=>{requests++;return handler?handler(r):r.fulfill({json:response(r.request().postDataJSON().text)});});await page.goto(BASE+'/deid/');await page.locator('#service[data-state=ready]').waitFor();return{context,page,errors,requests:()=>requests};}
async function analyse(page){await page.locator('#run').click();await page.locator('#review:not([hidden])').waitFor();}
async function metadata(page){if(await page.locator('#tab-output').isVisible())await page.locator('#tab-output').click();await page.locator('#exportMenu summary').click();await page.locator('#copySummary').click();return JSON.parse(await page.evaluate(()=>window.__copies.at(-1)));}

test('DeID review panes fit desktop and local apply/keep/confirm/undo preserve server policy',async()=>{const{page,context,errors,requests}=await open();await analyse(page);for(const id of['pane-source','pane-output','pane-review']){const box=await page.locator('#'+id).boundingBox();assert.ok(box.y>=0&&box.y+box.height<=905,id+' extends below working viewport '+JSON.stringify(box));}assert.equal(await page.locator('#result').textContent(),response().result_text);assert.match(await page.locator('#previewStatus').innerText(),/2 proposed spans/);await page.locator('input[data-id=d1]').uncheck();assert.match(await page.locator('#result').textContent(),/demo@example.invalid/);assert.match(await page.locator('#previewStatus').innerText(),/1 span is kept/);await page.locator('[data-confirm=d0]').click();assert.match(await page.locator('#previewStatus').innerText(),/decisions reviewed/);const meta=await metadata(page);assert.equal(meta.review_status,'detected_spans_reviewed');assert.equal(meta.kept_original_spans,1);assert.equal(meta.review_required,true);assert.ok(!('output_text'in meta));await page.locator('#undo').click();await page.locator('#undo').click();assert.equal(await page.locator('#result').textContent(),response().result_text);assert.equal(requests(),1);assert.deepEqual(errors,[]);if(process.env.UI_SCREENSHOTS_DIR){await mkdir(process.env.UI_SCREENSHOTS_DIR,{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:resolve(process.env.UI_SCREENSHOTS_DIR,'deid-review-'+(process.env.UI_BROWSER||'chromium')+'-desktop.png')});}await context.close();});

test('DeID manual redaction converts UTF16 selection to codepoints and rejects overlap without altering the draft',async()=>{const{page,context,requests}=await open();await analyse(page);await page.locator('#editView').click();await page.locator('#text').evaluate(el=>{const i=el.value.indexOf('ZX91');el.setSelectionRange(i,i+4);});await page.locator('#manual').click();assert.match(await page.locator('#result').textContent(),/\[REDACTED:MANUAL\]/);const meta=await metadata(page);const manual=meta.decisions.find(e=>e.origin==='manual');assert.deepEqual(manual.span,span(source,'ZX91'));assert.equal(manual.reviewed,true);assert.equal(meta.remaining_unreviewed,2);await page.locator('#editView').click();await page.locator('#text').evaluate(el=>{const i=el.value.indexOf('Avery');el.setSelectionRange(i,i+5);});const before=await page.locator('#result').textContent();await page.locator('#manual').click();assert.match(await page.locator('#message').innerText(),/overlaps/);assert.equal(await page.locator('#result').textContent(),before);await page.locator('#undo').click();assert.equal(await page.locator('#result').textContent(),response().result_text);assert.equal(requests(),1);await context.close();});

test('DeID explicit review export carries pending status and current output, without separate original values',async()=>{const{page,context}=await open();await analyse(page);assert.equal(await page.evaluate(()=>window.__copies.length),0);await page.locator('#exportMenu summary').click();const pending=page.waitForEvent('download');await page.locator('#downloadReview').click();const file=await pending;const data=JSON.parse(await readFile(await file.path(),'utf8'));assert.equal(data.output_text,response().result_text);assert.equal(data.review_status,'unreviewed_draft');assert.equal(data.remaining_unreviewed,2);assert.equal(data.review_required,true);assert.ok(!('source_text'in data));assert.ok(data.decisions.every(e=>!('surface'in e)&&!('replacement'in e)));assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await page.locator('#text').inputValue(),'');assert.equal(await page.locator('#copyOutput').isDisabled(),true);await context.close();});

test('DeID rejects inconsistent and overlapping review metadata without exposing an exportable draft',async()=>{for(const variant of['replacement','overlap']){const{page,context}=await open(1440,900,r=>{const data=response();if(variant==='replacement')data.entities[0].replacement='wrong';else data.entities[1].span=[3,10];return r.fulfill({json:data});});await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('could not be verified'));assert.equal(await page.locator('#review').isVisible(),false);assert.equal(await page.locator('#copyOutput').isDisabled(),true);await context.close();}});

test('DeID mobile workflow fits320/375/390, uses16px inputs and44px actions, and keeps review/export reachable',async()=>{for(const width of[320,375,390]){const{page,context,errors}=await open(width,812);await analyse(page);assert.equal(await page.locator('#pane-review').isVisible(),true);assert.equal(await page.locator('#pane-source').isVisible(),false);await page.locator('#inspector [data-action=apply]').click();await page.locator('#inspector [data-action=keep]').click();assert.equal((await metadata(page)).remaining_unreviewed,0);await page.locator('#tab-source').click();await page.locator('#editView').click();const sizes=await page.evaluate(()=>({font:parseFloat(getComputedStyle(document.querySelector('#text')).fontSize),selectFont:parseFloat(getComputedStyle(document.querySelector('#mode')).fontSize),selectHeight:document.querySelector('#mode').getBoundingClientRect().height,run:document.querySelector('#run').getBoundingClientRect().height,overflow:document.documentElement.scrollWidth-innerWidth}));assert.equal(await page.locator('.source-link').isVisible(),false);assert.ok(sizes.font>=16&&sizes.selectFont>=16);assert.ok(sizes.selectHeight>=44&&sizes.run>=44);if(sizes.overflow>1)console.log('OVERFLOW',width,JSON.stringify(await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).map(e=>({tag:e.tagName,id:e.id,class:e.className,rect:e.getBoundingClientRect().toJSON()})).filter(e=>e.rect.width&&e.rect.right>innerWidth+1).slice(0,15))));if(sizes.overflow>1)console.log('SCROLLBOXES',JSON.stringify(await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(e=>e.getBoundingClientRect().width&&e.scrollWidth>e.clientWidth+1).map(e=>({id:e.id,tag:e.tagName,cls:e.className,width:e.clientWidth,scroll:e.scrollWidth,overflow:getComputedStyle(e).overflowX})))));assert.ok(sizes.overflow<=1,JSON.stringify(sizes));assert.deepEqual(errors,[]);if(process.env.UI_SCREENSHOTS_DIR){await mkdir(process.env.UI_SCREENSHOTS_DIR,{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:resolve(process.env.UI_SCREENSHOTS_DIR,'deid-review-'+(process.env.UI_BROWSER||'chromium')+'-'+width+'.png')});await page.locator('#tab-review').click();await page.screenshot({path:resolve(process.env.UI_SCREENSHOTS_DIR,'deid-decisions-'+(process.env.UI_BROWSER||'chromium')+'-'+width+'.png')});}await context.close();}});
