import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
const engines=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const engine=engines[process.env.BROWSER_ENGINE||'chromium'];
const ROOT=resolve(process.env.DEMO_SOURCES_ROOT||process.cwd(),'mta-scan/static');
const ORIGIN='https://stelioszach.com';
let browser;
before(async()=>{browser=await engine.launch({executablePath:process.env.CHROME_EXECUTABLE||undefined});});
after(async()=>{await browser?.close();});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jOe8AAAAASUVORK5CYII=','base64');
const observation={stop_id:'synthetic-a',stop_name:'Synthetic station',route_id:'A',anomaly_score:.9,headway_sec:180,predicted_headway_sec:90,observed_utc:'2026-09-22T20:00:00Z',reasons:['Synthetic fixture only']};
const snapshot={generated_utc:'2026-09-22T20:00:10Z',live:{state:'live',feeds_ok:8,feeds_total:8,last_observed_age_sec:10,poll_seconds:30},counters:{stations_reporting:1,scored_rows:12,anomalies:1,anomalies_high:1},map:{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[-73.95,40.76]},properties:observation}]},anomalies:[observation],model:{maturity:'warm'},storage:{rows:12,bytes_human:'2 KB',max_bytes_human:'400 MB',retention_hours:48}};
async function open({width=1440,token='pk.synthetic.fixture',mapFails=false}={}){
 const context=await browser.newContext({viewport:{width,height:1000},isMobile:width<600,hasTouch:width<600,deviceScaleFactor:2,reducedMotion:'reduce',acceptDownloads:true});
 const calls=[];await context.route('**/*',async route=>{
  const u=new URL(route.request().url());
  if(u.origin==='https://api.mapbox.com'){calls.push(u);return mapFails?route.abort():route.fulfill({body:png,contentType:'image/png'});}
  if(u.origin==='https://tile.openstreetmap.org')return route.fulfill({body:png,contentType:'image/png'});
  if(u.origin!==ORIGIN)return route.abort();
  const rel=u.pathname.replace('/demos/mta-scan/','');
  if(rel==='api/state')return route.fulfill({json:snapshot});
  if(rel==='map-config.json')return route.fulfill({json:{publicToken:token}});
  const path=resolve(ROOT,rel||'index.html');
  if(!path.startsWith(ROOT+sep))return route.fulfill({status:404,body:''});
  try{return route.fulfill({body:await readFile(path),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[extname(path)]||'application/octet-stream'});}catch{return route.fulfill({status:404,body:''});}
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(ORIGIN+'/demos/mta-scan/');await page.locator('#exportSnapshot:enabled').waitFor();return{page,context,errors,calls};
}
test('Mapbox uses retina512 tiles and fixed styles with logo and required attribution',async()=>{const{page,context,calls,errors}=await open();await page.locator('#mapStyle:enabled').waitFor();await page.waitForFunction(()=>document.querySelectorAll('.leaflet-tile-loaded').length>0);assert.ok(calls.length>0);assert.ok(calls.every(u=>u.pathname.includes('/tiles/512/')&&u.pathname.endsWith('@2x')));assert.equal(await page.locator('#mapboxLogo').isVisible(),true);assert.match(await page.locator('.leaflet-control-attribution').innerText(),/Mapbox.*OpenStreetMap.*Improve this map/);await page.locator('#mapStyle').selectOption('streets');await page.waitForFunction(()=>document.querySelector('#mapProviderStatus').textContent.includes('Streets'));assert.ok(calls.some(u=>u.pathname.includes('streets-v12')));assert.deepEqual(errors,[]);await context.close();});
test('secret config is never sent to Mapbox, fallback is visible and observations survive',async()=>{const{page,context,calls,errors}=await open({token:'sk.synthetic.secret'});await page.locator('#mapProviderStatus').filter({hasText:'fallback'}).waitFor();assert.equal(calls.length,0);assert.equal(await page.locator('#mapStyle').isDisabled(),true);assert.equal(await page.locator('#mapboxLogo').isVisible(),false);assert.equal(await page.locator('#anoms li[role=button]').count(),1);assert.deepEqual(errors,[]);await context.close();});
test('failed Mapbox tiles fall back once without losing live observations',async()=>{const{page,context,calls,errors}=await open({mapFails:true});await page.locator('#mapProviderStatus').filter({hasText:'fallback'}).waitFor();const count=calls.length;await page.waitForTimeout(100);assert.equal(calls.length,count);assert.equal(await page.locator('#anoms li[role=button]').count(),1);assert.deepEqual(errors,[]);await context.close();});
test('export is explicit and contains the actual filtered live snapshot, disabled during replay',async()=>{const{page,context,errors}=await open();let downloads=0;page.on('download',()=>downloads++);assert.equal(downloads,0);await page.locator('#stationSearch').fill('missing');const downloaded=page.waitForEvent('download');await page.locator('#exportSnapshot').click();const download=await downloaded;const data=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(data.exported_map_observations,0);assert.equal(data.window_counters.stations_reporting,1);assert.equal(data.filters.search,'missing');await page.locator('#resetFilters').click();await page.locator('#fitFiltered').click();await page.locator('#timeline:enabled').waitFor();await page.locator('#timeline').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#exportSnapshot').isDisabled(),true);assert.equal(await page.locator('#fitFiltered').isDisabled(),true);assert.deepEqual(errors,[]);await context.close();});
test('map workspace fits320and375px and provides44px primary touch controls',async()=>{for(const width of [320,375]){const{page,context,errors}=await open({width});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('#windowControls').evaluate(e=>e.open),false);assert.ok((await page.locator('#map').boundingBox()).y<460,'map starts in first phone viewport');await page.locator('#windowControls > summary').click();for(const id of ['refresh','pauseLive','mapStyle','exportSnapshot','fitFiltered']){const box=await page.locator('#'+id).boundingBox();assert.ok(box.height>=44,id+' touch height');}assert.deepEqual(errors,[]);await context.close();}});
test('snapshot export retains its successful window while a changed window is still loading',async()=>{const{page,context}=await open();let release;try{await page.route('**/api/state?*',async route=>{await new Promise(r=>release=r);try{await route.fulfill({json:snapshot});}catch{}});await page.locator('#win').selectOption('6h');await page.waitForFunction(()=>document.querySelector('#refresh').disabled);const waiting=page.waitForEvent('download');await page.locator('#exportSnapshot').click();const d=await waiting;const data=JSON.parse(await readFile(await d.path(),'utf8'));assert.equal(data.filters.window,'1h');}finally{release?.();await context.close();}});
test('sustained tile errors after initial success are visible as fallback',async()=>{const{page,context}=await open();try{await page.waitForFunction(()=>document.querySelectorAll('.leaflet-tile-loaded').length>0);await page.route('https://api.mapbox.com/**',route=>route.abort());await page.locator('.leaflet-control-zoom-in').click();await page.locator('#mapProviderStatus').filter({hasText:'fallback'}).waitFor({timeout:2000});assert.equal(await page.locator('#anoms li[role=button]').count(),1);}finally{await context.close();}});

test('mobile panning can be enabled and locked again without trapping page scroll',async()=>{const{page,context}=await open({width:375});try{await page.locator('#maphint').click();assert.equal(await page.locator('#lockMap').isVisible(),true);await page.locator('#lockMap').click();assert.equal(await page.locator('#maphint').isVisible(),true);assert.equal(await page.locator('#lockMap').isVisible(),false);}finally{await context.close();}});
